services:
  - name: flask-api
    type: web
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 5000
    disk:
      name: persistent-disk
      mountPath: /var/data
      sizeGB: 1